test = {   'name': 'q1_12_0',
    'points': [0, 0, 0, 0],
    'suites': [   {   'cases': [   {'code': '>>> pop_for_year(1972) == 3355562066\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> pop_for_year(2020) == 6765161289\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> pop_for_year(1989) == 4576679948\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> pop_for_year(2002) == 5514129422\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
