test = {   'name': 'q3_1_9',
    'points': [1, 1],
    'suites': [   {   'cases': [   {   'code': ">>> genre_and_distances.take(np.arange(7)).group('Genre').index_by('Genre')[my_assigned_genre][0].item('count') >= 4\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': ">>> my_assigned_genre_was_correct == (my_assigned_genre == 'thriller')\nFalse", 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
