test = {   'name': 'q7_8',
    'points': [0, 0],
    'suites': [   {   'cases': [   {   'code': ">>> # Please actually go on Ed and look at the threads.\n>>> # Looks like you didn't make a string.\n>>> type(secret) == str\nTrue",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> len(secret)\n5', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
