test = {   'name': 'q1_1',
    'points': [0, 0, 0, 0],
    'suites': [   {   'cases': [   {'code': '>>> type(sample_size) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(percent_V1) == float or type(percent_V1) == int\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 100 <= sample_size <= 500\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> 0 <= percent_V1 <= 100\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
