test = {   'name': 'q1_6',
    'points': [0, 0],
    'suites': [   {   'cases': [   {   'code': '>>> # Make sure regression_changes is a numpy array with 3 items!\n>>> len(regression_changes) == 3 and type(regression_changes) == np.ndarray\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> regression_changes.item(0) in set([0, 1, False, True])\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
