ARG VARIANT=3.10
FROM mcr.microsoft.com/devcontainers/python:${VARIANT}

#[Optional] If your pip requirements rarely change, uncomment this section to add them to the image.
#COPY .devcontainer/requirements.txt /tmp/pip-tmp/
#RUN pip3 --disable-pip-version-check --no-cache-dir install -r /tmp/pip-tmp/requirements.txt \
#   && rm -rf /tmp/pip-tmp