test = {   'name': 'q3_4',
    'points': [1, 1, 1, 1],
    'suites': [   {   'cases': [   {   'code': '>>> # It looks like you multiplied and subtracted in the wrong\n>>> # order.\n>>> sum(celsius_max_temperatures) != 356705.0\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> sum(celsius_max_temperatures)\n1280677.0', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(celsius_max_temperatures)\n65000', 'hidden': False, 'locked': False},
                                   {'code': '>>> celsius_max_temperatures.item(2003)\n20.0', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
